### ISSUE TITLE
dms2dec issue with hemisphere

### ISSUE THREAD

**Issue by cmaccoll** [AMBarbosa/unpackaged#5]
Hi, Im trying to convert decimal degree coordinates from the southern hemisphere (e.g. -28.4 x 150.9) to DMS but am receiving the following error message with no guidance on how to account for hemisphere from decimal degree data:

Warning message:
In dms2dec(some_data$latitude_dms) :
  Hemisphere not specified in position(s)

Any assistance greatly appreciated.
Chris

**Comment by AMBarbosa** [comment]
Hi, the `dms2dec` function converts DMS to decimal degrees for mapping. It's not designed to convert the other way around. Cheers,

**Comment by cmaccoll** [comment]
Oh ok, thanks for clarifying.
